# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBY_u_kysBEjmec5i5uNDijx7dQzrr3l
"""

pip install gradio tensorflow scikit-learn opencv-python pillow numpy

import gradio as gr
import numpy as np
import cv2
import pickle
import tensorflow as tf
from PIL import Image

# ==============================
# Load Models
# ==============================
satellite_model = tf.keras.models.load_model("satellite_damage_model.h5")

with open("tweet_urgency_model.pkl", "rb") as f:
    tweet_model = pickle.load(f)

with open("tfidf_vectorizer.pkl", "rb") as f:
    vectorizer = pickle.load(f)


# ==============================
# Prediction Functions
# ==============================
def analyze_disaster(image, tweet_text):
    if image is None or tweet_text.strip() == "":
        return "❌ Please upload an image AND enter a tweet."

    # ---- Satellite Image Processing ----
    img = np.array(image)
    img = cv2.resize(img, (224, 224))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    damage_prob = satellite_model.predict(img)[0][0]

    # ---- Tweet NLP Processing ----
    tweet_vec = vectorizer.transform([tweet_text])
    tweet_prob = tweet_model.predict_proba(tweet_vec)[0][1]

    # ---- Priority Score ----
    priority_score = 0.6 * damage_prob + 0.4 * tweet_prob

    if priority_score > 0.7:
        priority = "🔴 HIGH PRIORITY"
    elif priority_score > 0.4:
        priority = "🟠 MEDIUM PRIORITY"
    else:
        priority = "🟢 LOW PRIORITY"

    # ---- Output ----
    result = f"""
### 🚨 Disaster Response Priority

**🛰️ Satellite Damage Probability:** {damage_prob:.2f}
**🐦 Tweet Urgency Probability:** {tweet_prob:.2f}

### 📊 Final Decision
**Priority Score:** {priority_score:.2f}
**Priority Level:** {priority}

#### 🔎 Decision Logic
- 60% Satellite Damage Analysis
- 40% Social Media Urgency

This helps rescue teams act **faster and smarter**.
"""
    return result


# ==============================
# Gradio UI
# ==============================
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 🌍 AI-Assisted Disaster Response Prioritization
        ### Multi-Modal AI for Faster Rescue & Aid Distribution

        This system combines **satellite imagery** and **social media text analysis**
        to identify **high-priority disaster zones**.
        """
    )

    with gr.Row():
        with gr.Column():
            image_input = gr.Image(
                label="🛰️ Upload Satellite Image",
                type="pil"
            )

        with gr.Column():
            tweet_input = gr.Textbox(
                label="🐦 Disaster Tweet / Message",
                placeholder="People trapped after earthquake, urgent help needed!",
                lines=5
            )

    analyze_btn = gr.Button("🚀 Analyze Disaster Priority")

    output = gr.Markdown()

    analyze_btn.click(
        fn=analyze_disaster,
        inputs=[image_input, tweet_input],
        outputs=output
    )

    gr.Markdown(
        """
        ---
        **AI for Good | Disaster Response Decision Support System**
        Built for humanitarian impact 🌱
        """
    )

# ==============================
# Launch App
# ==============================
demo.launch()

